# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3faf025bfc782c128b41201c89dec3a8b64cea9e6f3b58c36a99887d7bf116d97f69949bbd17112954a73598b2a0dbea756d092a138f07d944ecc1a4286ee20e

test:
  secret_key_base: ebdf65957dfb6916abbe11285ee3e66f451bb5cc03a8ec90946e3ccad3721890df3342984054301a5adb94011ae748201bec22b47d9c5340fd9e046dd07e070d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
